# Generated by Django 3.2.5 on 2021-08-01 18:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMS_Lead_Data',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Number', models.CharField(db_index=True, max_length=12)),
                ('Type', models.CharField(db_index=True, max_length=20)),
                ('Timezone', models.CharField(db_index=True, max_length=80)),
                ('First', models.CharField(db_index=True, max_length=100)),
                ('Last', models.CharField(db_index=True, max_length=100)),
                ('Address', models.CharField(db_index=True, max_length=254)),
                ('City', models.CharField(db_index=True, max_length=254)),
                ('State', models.CharField(db_index=True, max_length=254)),
                ('Zip', models.CharField(db_index=True, max_length=254)),
                ('PropertyID', models.CharField(db_index=True, max_length=254)),
                ('UploadDate', models.CharField(db_index=True, max_length=254)),
                ('SMSMessage1', models.CharField(db_index=True, max_length=511)),
                ('SMSStatus', models.BooleanField(blank=True, default=False)),
                ('SMSTimeStamp', models.CharField(blank=True, max_length=100, null=True)),
                ('ContactCallable', models.CharField(blank=True, db_index=True, max_length=255)),
                ('UploadedToVoiceCampaign', models.CharField(blank=True, db_index=True, max_length=255)),
                ('ZipCodeAutomaticTimeZone', models.CharField(blank=True, db_index=True, max_length=255)),
                ('CallRecordLastAttempt_Number', models.CharField(blank=True, db_index=True, max_length=255)),
                ('CallRecordLastResult_Number', models.CharField(blank=True, db_index=True, max_length=255)),
                ('CallRecordLastAgentWrapup_Number', models.CharField(blank=True, db_index=True, max_length=255)),
                ('SmsLastAttempt_Number', models.CharField(blank=True, db_index=True, max_length=255)),
                ('SmsLastResult_Number', models.CharField(blank=True, db_index=True, max_length=255)),
                ('Callable_Number', models.CharField(blank=True, db_index=True, max_length=255)),
                ('AutomaticTimeZone_Number', models.CharField(blank=True, db_index=True, max_length=255)),
                ('sentSMSId', models.UUIDField(db_index=True, null=True)),
                ('queued', models.BooleanField(db_index=True, default=True)),
            ],
        ),
    ]
