# Generated by Django 3.0 on 2021-09-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_lead', '0002_djangojob_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sent_call_list',
            name='campaign',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sms_queued',
            name='campaign',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sms_successful',
            name='campaign',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
