# Generated by Django 3.0 on 2021-09-14 18:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sms_lead', '0002_auto_20210903_0905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=254, null=True)),
                ('number', models.CharField(blank=True, db_index=True, max_length=254, null=True)),
                ('Call_List_ID', models.CharField(db_index=True, max_length=254, null=True)),
                ('zillow_list_id', models.CharField(db_index=True, max_length=254, null=True)),
                ('start', models.CharField(db_index=True, max_length=254, null=True)),
                ('end', models.CharField(db_index=True, max_length=254, null=True)),
                ('freaquency_seconds', models.IntegerField(default=0)),
                ('freaquency_minutes', models.IntegerField(default=0)),
                ('freaquency_hours', models.IntegerField(default=0)),
                ('download_freaquency_minutes', models.IntegerField(default=0)),
                ('purecloud_client_id', models.CharField(max_length=255)),
                ('purecloud_client_secret', models.CharField(max_length=255)),
                ('send_texts_scheduler_uuid', models.CharField(blank=True, db_index=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='DjangoJob',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=254)),
                ('next_run_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('job_state', models.BinaryField()),
            ],
            options={
                'ordering': ('next_run_time',),
            },
        ),
        migrations.AddField(
            model_name='sent_call_list',
            name='campaign',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sms_queued',
            name='campaign',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sms_successful',
            name='campaign',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sent_call_list',
            name='sentSMSId',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='sms_queued',
            name='sentSMSId',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='sms_successful',
            name='sentSMSId',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='DjangoJobExecution',
            fields=[
                ('id', models.BigAutoField(help_text='Unique ID for this job execution.', primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Started execution', 'Started execution'), ('Error!', 'Error!'), ('Executed', 'Executed')], help_text='The current status of this job execution.', max_length=50)),
                ('run_time', models.DateTimeField(db_index=True, help_text='Date and time at which this job was executed.')),
                ('duration', models.DecimalField(decimal_places=2, default=None, help_text='Total run time of this job (in seconds).', max_digits=15, null=True)),
                ('finished', models.DecimalField(decimal_places=2, default=None, help_text='Timestamp at which this job was finished.', max_digits=15, null=True)),
                ('exception', models.CharField(help_text='Details of exception that occurred during job execution (if any).', max_length=1000, null=True)),
                ('traceback', models.TextField(help_text='Traceback of exception that occurred during job execution (if any).', null=True)),
                ('job', models.ForeignKey(help_text='The job that this execution relates to.', on_delete=django.db.models.deletion.CASCADE, to='sms_lead.DjangoJob')),
            ],
            options={
                'ordering': ('-run_time',),
            },
        ),
    ]
