# Generated by Django 3.0 on 2021-09-14 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_lead', '0003_auto_20210914_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='Call_List_ID',
            field=models.CharField(blank=True, db_index=True, max_length=254, null=True),
        ),
    ]
