# Generated by Django 3.0 on 2021-09-14 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_lead', '0003_auto_20210913_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='djangojob',
            name='name',
            field=models.CharField(db_index=True, default='Zillow Time', max_length=254),
            preserve_default=False,
        ),
    ]
