# Generated by Django 3.0 on 2021-10-27 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_lead', '0004_auto_20210914_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sent_call_list',
            name='Address',
            field=models.CharField(blank=True, db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='sent_call_list',
            name='City',
            field=models.CharField(blank=True, db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='sent_call_list',
            name='First',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sent_call_list',
            name='Last',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sent_call_list',
            name='Number',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='sent_call_list',
            name='PropertyID',
            field=models.CharField(blank=True, db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='sent_call_list',
            name='SMSMessage1',
            field=models.CharField(blank=True, db_index=True, max_length=511),
        ),
        migrations.AlterField(
            model_name='sent_call_list',
            name='State',
            field=models.CharField(blank=True, db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='sent_call_list',
            name='Timezone',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='sent_call_list',
            name='Type',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='sent_call_list',
            name='UploadDate',
            field=models.CharField(blank=True, db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='sent_call_list',
            name='Zip',
            field=models.CharField(blank=True, db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='sms_queued',
            name='Address',
            field=models.CharField(blank=True, db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='sms_queued',
            name='City',
            field=models.CharField(blank=True, db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='sms_queued',
            name='First',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sms_queued',
            name='Last',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sms_queued',
            name='Number',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='sms_queued',
            name='PropertyID',
            field=models.CharField(blank=True, db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='sms_queued',
            name='SMSMessage1',
            field=models.CharField(blank=True, db_index=True, max_length=511),
        ),
        migrations.AlterField(
            model_name='sms_queued',
            name='State',
            field=models.CharField(blank=True, db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='sms_queued',
            name='Timezone',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='sms_queued',
            name='Type',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='sms_queued',
            name='UploadDate',
            field=models.CharField(blank=True, db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='sms_queued',
            name='Zip',
            field=models.CharField(blank=True, db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='sms_successful',
            name='Address',
            field=models.CharField(blank=True, db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='sms_successful',
            name='City',
            field=models.CharField(blank=True, db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='sms_successful',
            name='First',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sms_successful',
            name='Last',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sms_successful',
            name='Number',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='sms_successful',
            name='PropertyID',
            field=models.CharField(blank=True, db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='sms_successful',
            name='SMSMessage1',
            field=models.CharField(blank=True, db_index=True, max_length=511),
        ),
        migrations.AlterField(
            model_name='sms_successful',
            name='State',
            field=models.CharField(blank=True, db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='sms_successful',
            name='Timezone',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='sms_successful',
            name='Type',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='sms_successful',
            name='UploadDate',
            field=models.CharField(blank=True, db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='sms_successful',
            name='Zip',
            field=models.CharField(blank=True, db_index=True, max_length=254),
        ),
    ]
