# Generated by Django 3.0 on 2021-09-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_lead', '0004_djangojob_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sent_call_list',
            name='Number',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='sms_queued',
            name='Number',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='sms_successful',
            name='Number',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
