# Generated by Django 3.0 on 2021-09-03 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.CharField(db_index=True, default='ffffff', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='first',
            field=models.CharField(db_index=True, default='gggggggg', max_length=60),
            preserve_default=False,
        ),
    ]
